# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
version: 2
enable-beta-ecosystems: true
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/prepare-action"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      # Check for updates to pip packages every weekday
      interval: "daily"
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-major"]
...
